### PR TITLE
I'm putting some new stuff here. figgerin' the gittin' n hubbin'

### PR DESCRIPTION
**Pull request by jsoldenwagner**
@rgiordan

### CODE REVIEW

**Comment by jsoldenwagner** [comment]
I think this is a pretty good pull request.  Yup.

**Comment by jsoldenwagner** [comment]
Sure is a goodn'.  I like this new stuff very much.

**Comment by jsoldenwagner** [comment]
:open_mouth: emojis? why?

**Comment by rgiordan** [comment]
TODO: Write unit tests for this new code.  :ok_hand: :fire:

**Pull request merged**
